# Bootloader selection
BOOTLOADER = caterina
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
RGBLIGHT_LED_COUNT = 14
RGBLED_SPLIT = { 7, 7 }
